"""
Director bridge — convert clips.json to Remotion-ready src/data.ts.
Usage: python pipeline/generate_data_ts.py --in data/clips.json --out src/data.ts

Generates a TypeScript file matching the ShortsData interface defined in src/data.ts,
with strict audio-caption timing sync.
"""

import argparse
import json
import os
import sys


def escape_ts_string(s: str) -> str:
    """Escape a string for use in a TypeScript template literal or string."""
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def clip_to_ts(clip: dict, indent: str = "        ") -> str:
    """Convert a single clip dict to TypeScript object literal."""
    lines = [f"{indent}{{"]
    lines.append(f'{indent}  start: {clip["start"]},')
    lines.append(f'{indent}  end: {clip["end"]},')
    lines.append(f'{indent}  type: "{clip["type"]}",')

    overlay = clip.get("overlay", {})
    en = escape_ts_string(overlay.get("en", ""))
    kr = escape_ts_string(overlay.get("kr", ""))
    lines.append(f"{indent}  overlay: {{")
    lines.append(f'{indent}    en: "{en}",')
    lines.append(f'{indent}    kr: "{kr}",')
    lines.append(f"{indent}  }},")

    if "keyword" in clip:
        kw = escape_ts_string(clip["keyword"])
        lines.append(f'{indent}  keyword: "{kw}",')

    if "highlightColor" in clip:
        lines.append(f'{indent}  highlightColor: "{clip["highlightColor"]}",')

    if "videoSrc" in clip:
        lines.append(f'{indent}  videoSrc: "{escape_ts_string(clip["videoSrc"])}",')
    if "clipStartSec" in clip:
        lines.append(f'{indent}  clipStartSec: {clip["clipStartSec"]},')
    if "clipEndSec" in clip:
        lines.append(f'{indent}  clipEndSec: {clip["clipEndSec"]},')

    lines.append(f"{indent}}},")
    return "\n".join(lines)


def generate_data_ts(clips_data: dict) -> str:
    """Generate the full data.ts TypeScript source."""
    parts_ts = []

    for part in clips_data["parts"]:
        clips_ts = "\n".join(clip_to_ts(clip) for clip in part["clips"])
        parts_ts.append(f"""    {{
      id: "{part['id']}",
      clips: [
{clips_ts}
      ],
    }}""")

    parts_joined = ",\n".join(parts_ts)

    return f"""/**
 * This file is auto-generated by the Director Agent.
 * Do NOT edit manually — it will be overwritten on each render cycle.
 */

export interface Clip {{
  start: number;
  end: number;
  type: "hook" | "expression_raw" | "expression_blank" | "expression_reveal" | "wrapup";
  overlay: {{
    en: string;
    kr: string;
  }};
  keyword?: string;
  highlightColor?: string;
  // Source video for 3-pass playback (raw/blank/reveal share the same segment)
  videoSrc?: string;
  clipStartSec?: number;
  clipEndSec?: number;
}}

export interface Part {{
  id: string;
  clips: Clip[];
}}

export interface ShortsData {{
  parts: Part[];
}}

export const data: ShortsData = {{
  parts: [
{parts_joined},
  ],
}};
"""


def main():
    parser = argparse.ArgumentParser(description="Generate Remotion data.ts from clips JSON")
    parser.add_argument("--in", dest="input", required=True, help="Input clips JSON (or clips_fixed.json)")
    parser.add_argument("--out", required=True, help="Output TypeScript file path")
    args = parser.parse_args()

    with open(args.input, "r", encoding="utf-8") as f:
        clips_data = json.load(f)

    parts = clips_data.get("parts", [])
    if not parts:
        print("ERROR: No parts found in input", file=sys.stderr)
        sys.exit(1)

    print(f"  Generating data.ts for {len(parts)} parts...")

    ts_source = generate_data_ts(clips_data)

    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(ts_source)

    # Summary
    for part in parts:
        clip_count = len(part["clips"])
        duration = part["clips"][-1]["end"] if part["clips"] else 0
        print(f"    {part['id']}: {clip_count} clips, {duration:.1f}s")

    print(f"  Output: {args.out}")


if __name__ == "__main__":
    main()
