/**
 * This file is auto-generated by the Director Agent.
 * Do NOT edit manually — it will be overwritten on each render cycle.
 */

export interface Clip {
  start: number;
  end: number;
  type: "hook" | "expression" | "freeze_frame" | "wrapup";
  overlay: {
    en: string;
    kr: string;
  };
  highlightColor?: string;
}

export interface Part {
  id: string;
  clips: Clip[];
}

export interface ShortsData {
  parts: Part[];
}

// Placeholder data for development preview
export const data: ShortsData = {
  parts: [
    {
      id: "part1",
      clips: [
        {
          start: 0,
          end: 3,
          type: "hook",
          overlay: {
            en: "5 Key Expressions from Today's Briefing",
            kr: "오늘 브리핑의 핵심 표현 5가지",
          },
        },
        {
          start: 3,
          end: 15,
          type: "expression",
          overlay: {
            en: "CALL INTO QUESTION",
            kr: "~에 의문을 제기하다",
          },
          highlightColor: "#00BFFF",
        },
        {
          start: 15,
          end: 18,
          type: "freeze_frame",
          overlay: {
            en: "to cause doubt about something",
            kr: "무언가에 대해 의심을 갖게 만들다",
          },
        },
        {
          start: 18,
          end: 30,
          type: "expression",
          overlay: {
            en: "UNDERSCORE",
            kr: "강조하다",
          },
          highlightColor: "#FFD700",
        },
        {
          start: 30,
          end: 35,
          type: "wrapup",
          overlay: {
            en: "Like & Subscribe for more!",
            kr: "좋아요와 구독 부탁드려요!",
          },
        },
      ],
    },
  ],
};
