/**
 * This file is auto-generated by the Director Agent.
 * Do NOT edit manually — it will be overwritten on each render cycle.
 */

export interface Clip {
  start: number;
  end: number;
  type: "hook" | "expression_raw" | "expression_blank" | "expression_reveal" | "wrapup";
  overlay: {
    en: string;
    kr: string;
  };
  keyword?: string;
  highlightColor?: string;
  // Source video for 3-pass playback (raw/blank/reveal share the same segment)
  videoSrc?: string;
  clipStartSec?: number;
  clipEndSec?: number;
}

export interface Part {
  id: string;
  clips: Clip[];
}

export interface ShortsData {
  parts: Part[];
}

export const data: ShortsData = {
  parts: [
    {
      id: "part1",
      clips: [
        {
          start: 0.0,
          end: 3.0,
          type: "hook",
          overlay: {
            en: "5 Must-Know WH Briefing Expressions",
            kr: "백악관 브리핑 필수 표현 5가지",
          },
        },
        {
          start: 3.0,
          end: 8.0,
          type: "expression_raw",
          overlay: {
            en: "more affordable for working Americans. The\npresident will visit Thermoffisher The",
            kr: "",
          },
          keyword: "REITERATE",
          highlightColor: "#00BFFF",
          videoSrc: "video/source.mp4",
          clipStartSec: 22.16,
          clipEndSec: 185.27,
        },
        {
          start: 8.0,
          end: 12.0,
          type: "expression_blank",
          overlay: {
            en: "more affordable for working Americans. The\npresident will visit Thermoffisher The",
            kr: "['reiterate'의 한국어 설명]",
          },
          keyword: "REITERATE",
          videoSrc: "video/source.mp4",
          clipStartSec: 22.16,
          clipEndSec: 185.27,
        },
        {
          start: 12.0,
          end: 17.0,
          type: "expression_reveal",
          overlay: {
            en: "[Definition of 'reiterate']",
            kr: "['reiterate'의 한국어 설명]",
          },
          keyword: "REITERATE",
          highlightColor: "#00BFFF",
          videoSrc: "video/source.mp4",
          clipStartSec: 22.16,
          clipEndSec: 185.27,
        },
        {
          start: 17.0,
          end: 22.0,
          type: "expression_raw",
          overlay: {
            en: "Iranian missile industry to the ground.\nensure their terrorist proxies can no",
            kr: "",
          },
          keyword: "REST ASSURED",
          highlightColor: "#FFD700",
          videoSrc: "video/source.mp4",
          clipStartSec: 185.28,
          clipEndSec: 324.71,
        },
        {
          start: 22.0,
          end: 26.0,
          type: "expression_blank",
          overlay: {
            en: "Iranian missile industry to the ground.\nensure their terrorist proxies can no",
            kr: "['rest assured'의 한국어 설명]",
          },
          keyword: "REST ASSURED",
          videoSrc: "video/source.mp4",
          clipStartSec: 185.28,
          clipEndSec: 324.71,
        },
        {
          start: 26.0,
          end: 31.0,
          type: "expression_reveal",
          overlay: {
            en: "[Definition of 'rest assured']",
            kr: "['rest assured'의 한국어 설명]",
          },
          keyword: "REST ASSURED",
          highlightColor: "#FFD700",
          videoSrc: "video/source.mp4",
          clipStartSec: 185.28,
          clipEndSec: 324.71,
        },
        {
          start: 31.0,
          end: 36.0,
          type: "expression_raw",
          overlay: {
            en: "roles, and Congress needs to pass this.\nNumber three, the Save America Act Number",
            kr: "",
          },
          keyword: "EXECUTIVE ORDER",
          highlightColor: "#FF6B6B",
          videoSrc: "video/source.mp4",
          clipStartSec: 346.8,
          clipEndSec: 437.67,
        },
        {
          start: 36.0,
          end: 40.0,
          type: "expression_blank",
          overlay: {
            en: "roles, and Congress needs to pass this.\nNumber three, the Save America Act Number",
            kr: "['executive order'의 한국어 설명]",
          },
          keyword: "EXECUTIVE ORDER",
          videoSrc: "video/source.mp4",
          clipStartSec: 346.8,
          clipEndSec: 437.67,
        },
        {
          start: 40.0,
          end: 45.0,
          type: "expression_reveal",
          overlay: {
            en: "[Definition of 'executive order']",
            kr: "['executive order'의 한국어 설명]",
          },
          keyword: "EXECUTIVE ORDER",
          highlightColor: "#FF6B6B",
          videoSrc: "video/source.mp4",
          clipStartSec: 346.8,
          clipEndSec: 437.67,
        },
        {
          start: 45.0,
          end: 50.0,
          type: "expression_raw",
          overlay: {
            en: "necessary at the appropriate time. And if\nthis was something that was And if this",
            kr: "",
          },
          keyword: "IN TERMS OF",
          highlightColor: "#7B68EE",
          videoSrc: "video/source.mp4",
          clipStartSec: 762.8,
          clipEndSec: 786.949,
        },
        {
          start: 50.0,
          end: 54.0,
          type: "expression_blank",
          overlay: {
            en: "necessary at the appropriate time. And if\nthis was something that was And if this",
            kr: "['in terms of'의 한국어 설명]",
          },
          keyword: "IN TERMS OF",
          videoSrc: "video/source.mp4",
          clipStartSec: 762.8,
          clipEndSec: 786.949,
        },
        {
          start: 54.0,
          end: 59.0,
          type: "expression_reveal",
          overlay: {
            en: "[Definition of 'in terms of']",
            kr: "['in terms of'의 한국어 설명]",
          },
          keyword: "IN TERMS OF",
          highlightColor: "#7B68EE",
          videoSrc: "video/source.mp4",
          clipStartSec: 762.8,
          clipEndSec: 786.949,
        },
        {
          start: 59.0,
          end: 64.0,
          type: "expression_raw",
          overlay: {
            en: "energy through the strait of Hermoose. So\nthe president I think is making quite So",
            kr: "",
          },
          keyword: "WITH RESPECT TO",
          highlightColor: "#00FA9A",
          videoSrc: "video/source.mp4",
          clipStartSec: 967.12,
          clipEndSec: 982.79,
        },
        {
          start: 64.0,
          end: 68.0,
          type: "expression_blank",
          overlay: {
            en: "energy through the strait of Hermoose. So\nthe president I think is making quite So",
            kr: "['with respect to'의 한국어 설명]",
          },
          keyword: "WITH RESPECT TO",
          videoSrc: "video/source.mp4",
          clipStartSec: 967.12,
          clipEndSec: 982.79,
        },
        {
          start: 68.0,
          end: 73.0,
          type: "expression_reveal",
          overlay: {
            en: "[Definition of 'with respect to']",
            kr: "['with respect to'의 한국어 설명]",
          },
          keyword: "WITH RESPECT TO",
          highlightColor: "#00FA9A",
          videoSrc: "video/source.mp4",
          clipStartSec: 967.12,
          clipEndSec: 982.79,
        },
        {
          start: 73.0,
          end: 78.0,
          type: "wrapup",
          overlay: {
            en: "Follow for daily real-world English!",
            kr: "매일 실전 영어 표현을 받아보세요!",
          },
        },
      ],
    },
    {
      id: "part2",
      clips: [
        {
          start: 0.0,
          end: 3.0,
          type: "hook",
          overlay: {
            en: "5 Must-Know WH Briefing Expressions",
            kr: "백악관 브리핑 필수 표현 5가지",
          },
        },
        {
          start: 3.0,
          end: 8.0,
          type: "expression_raw",
          overlay: {
            en: "addressed this in the last briefing. This\nwas a feeling the president had This was a",
            kr: "",
          },
          keyword: "GOOD FAITH",
          highlightColor: "#00BFFF",
          videoSrc: "video/source.mp4",
          clipStartSec: 1074.32,
          clipEndSec: 1120.31,
        },
        {
          start: 8.0,
          end: 12.0,
          type: "expression_blank",
          overlay: {
            en: "addressed this in the last briefing. This\nwas a feeling the president had This was a",
            kr: "['good faith'의 한국어 설명]",
          },
          keyword: "GOOD FAITH",
          videoSrc: "video/source.mp4",
          clipStartSec: 1074.32,
          clipEndSec: 1120.31,
        },
        {
          start: 12.0,
          end: 17.0,
          type: "expression_reveal",
          overlay: {
            en: "[Definition of 'good faith']",
            kr: "['good faith'의 한국어 설명]",
          },
          keyword: "GOOD FAITH",
          highlightColor: "#00BFFF",
          videoSrc: "video/source.mp4",
          clipStartSec: 1074.32,
          clipEndSec: 1120.31,
        },
        {
          start: 17.0,
          end: 22.0,
          type: "expression_raw",
          overlay: {
            en: "filibuster. He says that's the reality.",
            kr: "",
          },
          keyword: "FILIBUSTER",
          highlightColor: "#FFD700",
          videoSrc: "video/source.mp4",
          clipStartSec: 1196.789,
          clipEndSec: 1196.799,
        },
        {
          start: 22.0,
          end: 26.0,
          type: "expression_blank",
          overlay: {
            en: "filibuster. He says that's the reality.",
            kr: "['filibuster'의 한국어 설명]",
          },
          keyword: "FILIBUSTER",
          videoSrc: "video/source.mp4",
          clipStartSec: 1196.789,
          clipEndSec: 1196.799,
        },
        {
          start: 26.0,
          end: 31.0,
          type: "expression_reveal",
          overlay: {
            en: "[Definition of 'filibuster']",
            kr: "['filibuster'의 한국어 설명]",
          },
          keyword: "FILIBUSTER",
          highlightColor: "#FFD700",
          videoSrc: "video/source.mp4",
          clipStartSec: 1196.789,
          clipEndSec: 1196.799,
        },
        {
          start: 31.0,
          end: 36.0,
          type: "expression_raw",
          overlay: {
            en: "said? Look, I think President Trump the\nLook, I think President Trump the Look, I",
            kr: "",
          },
          keyword: "ON THE TABLE",
          highlightColor: "#FF6B6B",
          videoSrc: "video/source.mp4",
          clipStartSec: 1199.52,
          clipEndSec: 1223.27,
        },
        {
          start: 36.0,
          end: 40.0,
          type: "expression_blank",
          overlay: {
            en: "said? Look, I think President Trump the\nLook, I think President Trump the Look, I",
            kr: "['on the table'의 한국어 설명]",
          },
          keyword: "ON THE TABLE",
          videoSrc: "video/source.mp4",
          clipStartSec: 1199.52,
          clipEndSec: 1223.27,
        },
        {
          start: 40.0,
          end: 45.0,
          type: "expression_reveal",
          overlay: {
            en: "[Definition of 'on the table']",
            kr: "['on the table'의 한국어 설명]",
          },
          keyword: "ON THE TABLE",
          highlightColor: "#FF6B6B",
          videoSrc: "video/source.mp4",
          clipStartSec: 1199.52,
          clipEndSec: 1223.27,
        },
        {
          start: 45.0,
          end: 50.0,
          type: "expression_raw",
          overlay: {
            en: "Yes. Yes, I have spoken to the president\nYes, I have spoken to the president Yes, I",
            kr: "",
          },
          keyword: "NATIONAL SECURITY",
          highlightColor: "#7B68EE",
          videoSrc: "video/source.mp4",
          clipStartSec: 1259.039,
          clipEndSec: 1293.59,
        },
        {
          start: 50.0,
          end: 54.0,
          type: "expression_blank",
          overlay: {
            en: "Yes. Yes, I have spoken to the president\nYes, I have spoken to the president Yes, I",
            kr: "['national security'의 한국어 설명]",
          },
          keyword: "NATIONAL SECURITY",
          videoSrc: "video/source.mp4",
          clipStartSec: 1259.039,
          clipEndSec: 1293.59,
        },
        {
          start: 54.0,
          end: 59.0,
          type: "expression_reveal",
          overlay: {
            en: "[Definition of 'national security']",
            kr: "['national security'의 한국어 설명]",
          },
          keyword: "NATIONAL SECURITY",
          highlightColor: "#7B68EE",
          videoSrc: "video/source.mp4",
          clipStartSec: 1259.039,
          clipEndSec: 1293.59,
        },
        {
          start: 59.0,
          end: 64.0,
          type: "expression_raw",
          overlay: {
            en: "look forward to the coalition expanding.",
            kr: "",
          },
          keyword: "COALITION",
          highlightColor: "#00FA9A",
          videoSrc: "video/source.mp4",
          clipStartSec: 1500.87,
          clipEndSec: 1500.88,
        },
        {
          start: 64.0,
          end: 68.0,
          type: "expression_blank",
          overlay: {
            en: "look forward to the coalition expanding.",
            kr: "['coalition'의 한국어 설명]",
          },
          keyword: "COALITION",
          videoSrc: "video/source.mp4",
          clipStartSec: 1500.87,
          clipEndSec: 1500.88,
        },
        {
          start: 68.0,
          end: 73.0,
          type: "expression_reveal",
          overlay: {
            en: "[Definition of 'coalition']",
            kr: "['coalition'의 한국어 설명]",
          },
          keyword: "COALITION",
          highlightColor: "#00FA9A",
          videoSrc: "video/source.mp4",
          clipStartSec: 1500.87,
          clipEndSec: 1500.88,
        },
        {
          start: 73.0,
          end: 78.0,
          type: "wrapup",
          overlay: {
            en: "Follow for daily real-world English!",
            kr: "매일 실전 영어 표현을 받아보세요!",
          },
        },
      ],
    },
  ],
};
